"""Remove budget_period column - budgets are monthly only

Revision ID: 178f48f7c8e8
Revises: 44980faba096
Create Date: 2025-11-18 13:58:06.564153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178f48f7c8e8'
down_revision = '44980faba096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_column('budget_period')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_period', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
