"""Add is_admin field to users table

Revision ID: 44980faba096
Revises: 9ba776930ad3
Create Date: 2025-11-04 15:41:18.392376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44980faba096'
down_revision = '9ba776930ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
