"""Add user_participates field to Transaction model

Revision ID: 9ba776930ad3
Revises: ab42f25da337
Create Date: 2025-11-02 18:09:41.241940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba776930ad3'
down_revision = 'ab42f25da337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_participates', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('user_participates')

    # ### end Alembic commands ###
