"""Fix Budget model - add is_active, remove start_date and end_date

Revision ID: ab42f25da337
Revises: b19be94d78fc
Create Date: 2025-10-30 20:27:52.731754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab42f25da337'
down_revision = 'b19be94d78fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        # Just drop the columns, no need to modify foreign key constraint
        batch_op.drop_column('start_date')
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        # Add back the columns we removed
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=False))

    # ### end Alembic commands ###
