"""Add alert fields to Budget model

Revision ID: b19be94d78fc
Revises: 68d1e1acb2f3
Create Date: 2025-10-30 13:00:52.107917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19be94d78fc'
down_revision = '68d1e1acb2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_threshold', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('notifications_enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_column('notifications_enabled')
        batch_op.drop_column('alert_threshold')

    # ### end Alembic commands ###
